require("colehpage.plugin_config.litee")
require("colehpage.plugin_config.lualine")
require("colehpage.plugin_config.nvim-tree")
require("colehpage.plugin_config.treesitter")
require("colehpage.plugin_config.lsp-config")
require("colehpage.plugin_config.mason")
-- require("colehpage.plugin_config.illuminate")
require("colehpage.plugin_config.nvim-cmp")
require("colehpage.plugin_config.alpha")
require("colehpage.plugin_config.virt-column")
require("colehpage.plugin_config.neodev")
require("colehpage.plugin_config.gitsigns")
