#!/bin/bash

source "$HOME/.config/colors.sh"

rgb_to_argb() {
    rgb_color="$1"
    argb_color="0xff${rgb_color:2}"
    echo "$argb_color"
}

options=(
	style=round
	width=4
	hidpi=on
    active_color=$(rgb_to_argb $COLOR_ACCENT_BRIGHT)
    inactive_color=$(rgb_to_argb $COLOR_BACKGROUND)
)

borders "${options[@]}"
