#!/bin/bash

source "$HOME/.config/colors.sh"

export GREY=$COLOR_GREY
export TRANSPARENT=$COLOR_TRANSPARENT

# ITEMS TOKYO NIGHT GOGH
export APPLE_COLOR=$COLOR_WHITE
export CPU_COLOR=$COLOR_RED
export MEMORY_COLOR=$COLOR_BLUE
export HD_COLOR=$COLOR_YELLOW
export VOLUME_COLOR=$COLOR_GREEN
export BATTERY_COLOR=$COLOR_WHITE
export GITHUB_COLOR=$COLOR_CYAN
export BREW_COLOR=$COLOR_YELLOW
export CALENDAR_COLOR=$COLOR_BLUE
export TIME_COLOR=$COLOR_RED

# ITEMS
export ITEM_BACKGROUND_COLOR=0xff1b1d27
export BAR_COLOR=0xff191a22
export BAR_BORDER_COLOR=0xff414556 #0xa024273a
export BAR_OUTER_BORDER_COLOR=0xff8f8f8f
export ICON_COLOR=0xffbac3f0 # Color of all icons
export LABEL_COLOR=0xffbac3f0 # Color of all labels
export BACKGROUND_1=0x603c3e4f
export BACKGROUND_2=0x60494d64

export POPUP_BACKGROUND_COLOR=0xff1e1e2e
export POPUP_BORDER_COLOR=$COLOR_WHITE

export SHADOW_COLOR=$COLOR_BLACK