print("init.lua loaded")

require "colehpage.options"
require "colehpage.highlights"
require "colehpage.keymaps"
require "colehpage.plugins"
require "colehpage.colorscheme"
require "colehpage.plugins.ts-autotag"
require "colehpage.plugins.colorizer"

require "colehpage.lsp"
require "colehpage.plugins.lspkind"
require "colehpage.plugins.lsp-colors"
require "colehpage.plugins.mason"

require "colehpage.plugins.neosolarized"
require "colehpage.plugins.cmp"
require "colehpage.plugins.telescope"
require "colehpage.plugins.treesitter"
require "colehpage.plugins.nvim-tree"
require "colehpage.plugins.autopairs"
require "colehpage.plugins.illuminate"
require "colehpage.plugins.comment"
require "colehpage.plugins.gitsigns"
require "colehpage.plugins.bufferline"
require "colehpage.plugins.lualine"
require "colehpage.plugins.toggleterm"
require "colehpage.plugins.project"
require "colehpage.plugins.impatient"
require "colehpage.plugins.indentline"
require "colehpage.plugins.dap"

-- require "colehpage.plugins.alpha"
