[colors.primary]
background = '0x0C0F14'
foreground = '0x98AFCB'

[colors.normal]
black =   '0x073642'
red =     '0xCC3333'
green =   '0x809900'
yellow =  '0xBF9000'
blue =    '0x336699'
magenta = '0xCC3399'
cyan =    '0x339999'
white =   '0xFAF3DD'

[colors.bright]
black =   '0x17212B'
red =     '0xFF6666'
green =   '0x99CC33'
yellow =  '0xFFD700'
blue =    '0x6699CC'
magenta = '0xFF66B3'
cyan =    '0x66CCCC'
white =   '0xFEF7E0'